### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by markseuffert** [richi/yellowcms-cli#2]
Hi Richi, 

did some improvement… please take what you like:

https://github.com/markseu/yellow-plugin-cli
- added update.ini for latest Yellow, makes installation easier 
- adapted for latest Yellow API, some things have changed
- updated for latest coding standard, makes all code look similar

PS: I didn't have a working email address, hope it's okay to open an Github issue.

**Comment by richi** [comment]
Great job!

I will be back to work in about a week, vacations in Germany are a little bit longish :)

The address shown here:

https://github.com/richi 

should actually work...
